### ISSUE TITLE
窗口拖动，图片缩放与垂直居中的问题

### ISSUE THREAD

**Issue by wing-kai** [wing-kai/Manga-Reader#1]
我想让我的阅读器，在单页模式显示时，
图片垂直居中显示，且尺寸不超出容器。

``` html
<div>
    <img src="./image.png" alt="image" />
</div>
```

``` css
div {
    display: flex;
    align-items: center;
    justify-content: center;
}

img {
    max-width: 100%;
    max-height: 100%;
}
```

不拖拉窗口的时候，图片可以按照预期样子显示。
但是一旦拖拉窗口，图片就会发生变形。不过刷新之后，又回恢复正常。

![ssss](https://cloud.githubusercontent.com/assets/9555713/12791933/4fe9b926-cae4-11e5-9b7c-2132adcbbc3b.gif)

如果改变dom结构，去掉`<img />`，让图片作为div的背景显示的话，
可以解决拖动变形的问题，但切换图片时，会有的闪烁效果，刺瞎狗眼。

![ssss](https://cloud.githubusercontent.com/assets/9555713/12792814/8660db20-cae8-11e5-8450-19bc8442a544.gif)

请问我该怎么做，既能防止图片变形，又不出现闪烁效果

[我在SegmentFault也发表了同样的问题](https://segmentfault.com/q/1010000004412334)
